add chnges

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -38,3 +38,42 @@ jobs:
           tags: |
             ${{ env.IMAGE_NAME }}:latest
             ${{ env.IMAGE_NAME }}:${{ github.sha }}
+  
+
+  deploy:
+    runs-on: ubuntu-latest
+    needs: build-and-push
+
+    steps:
+      - name: Debug SSH key
+        run: |
+          echo "Key length: $(echo '${{ secrets.SSH_PRIVATE_KEY }}' | wc -c)"
+          echo "Key starts with: $(echo '${{ secrets.SSH_PRIVATE_KEY }}' | head -c 30)"
+          echo "Key ends with: $(echo '${{ secrets.SSH_PRIVATE_KEY }}' | tail -c 30)"
+
+      - name: Deploy to Ubuntu server via SSH
+        uses: appleboy/ssh-action@v1
+        with:
+          host: ${{ secrets.SERVER_HOST }} # Replace with your server's IP address or hostname
+          username: ${{ secrets.SERVER_USER }} # Replace with your server's SSH username eg. ubuntu
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          debug: true
+          script: |
+            # Pull the latest image
+            docker pull ${{ env.IMAGE_NAME }}:latest
+
+            # Stop and remove existing container (if running)
+            docker stop materialmanagement || true
+            docker rm materialmanagement || true
+
+            # Run the new container
+            docker run -d \
+              --name materialmanagement \
+              --restart unless-stopped \
+              -p 8080:8080 \
+              -e ASPNETCORE_ENVIRONMENT=Production \
+              #-e "ConnectionStrings__DefaultConnection=${{ secrets.DB_CONNECTION_STRING }}" \
+              ${{ env.IMAGE_NAME }}:latest
+
+            # Clean up old images
+            docker image prune -f
